plugins {
  id 'java'
}

group = 'com.itson'
version = '1.0.0'
description = 'Scoreboard plugin for Paper'

repositories {
  mavenCentral()
  maven {
    name = 'papermc'
    url = 'https://repo.papermc.io/repository/maven-public/'
  }
  maven {
    name = 'placeholderapi'
    url = 'https://repo.extendedclip.com/content/repositories/placeholderapi/'
  }
}

dependencies {
  compileOnly libs.paper.api
  compileOnly 'me.clip:placeholderapi:2.12.3'

  testImplementation libs.junit.jupiter
  testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

java {
  toolchain {
    languageVersion = JavaLanguageVersion.of(25)
  }
}

tasks.withType(JavaCompile).configureEach {
  options.encoding = 'UTF-8'
  options.release = 25
}

tasks.named('processResources', ProcessResources).configure {
  def expansions = [
    name       : rootProject.name,
    version    : project.version,
    description: project.description,
    apiVersion : '26.2'
  ]
  inputs.properties expansions
  filesMatching('plugin.yml') {
    expand expansions
  }
}

tasks.named('test', Test) {
  useJUnitPlatform()
}
